services:
  server:
    build:
      context: matchmaking/server
      target: builder
    stop_signal: SIGINT
    hostname: server
    ports:
      - '8000:8000'

  solution:
    build:
      context: matchmaking/solution
    command: /bin/sh -c "sleep 5 && build/Solution"
    stop_signal: SIGINT